# Generated by Django 3.2.25 on 2026-01-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='description',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='status',
        ),
        migrations.AddField(
            model_name='slot',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='slot',
            name='name',
            field=models.CharField(default='Slot', max_length=100),
        ),
    ]
