# Generated by Django 3.2.25 on 2026-02-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0002_auto_20260128_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='status',
            field=models.CharField(default='available', max_length=20),
        ),
    ]
