# Generated by Django 3.2.25 on 2026-01-28 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_remove_description_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='tags',
        ),
    ]
