# Generated by Django 3.2.25 on 2026-02-02 05:27

import django.core.files.storage
from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_remove_tags_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/gallery/media/gallery/', location='C:\\Users\\dell\\Desktop\\admin_basic\\website-builder\\gallery\\media\\gallery'), upload_to=gallery.models.gallery_image_upload_path),
        ),
    ]
