# Generated by Django 3.2.25 on 2026-05-08 10:31

import django.core.files.storage
from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/services/media/icons/', location='C:\\Users\\dell\\Desktop\\website-builder\\services\\media\\icons'), upload_to=services.models.service_icon_upload_path),
        ),
    ]
