# Generated by Django 3.2.25 on 2026-01-28 16:18

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Blog = apps.get_model('blogs', 'Blog')
    for blog in Blog.objects.all():
        if not blog.slug:
            blog.slug = slugify(blog.title)
            blog.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20260128_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.RunPython(populate_slugs),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]