# Generated by Django 3.2.25 on 2026-05-08 10:31

import blogs.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_alter_blog_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/blogs/media/blogs/', location='C:\\Users\\dell\\Desktop\\website-builder\\blogs\\media\\blogs'), upload_to=blogs.models.blog_image_upload_path),
        ),
    ]
