# Generated by Django 3.2.25 on 2026-05-08 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
    ]
