# Generated by Django 5.2.10 on 2026-01-12 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=150, null=True)),
                ('author', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to='blog_images')),
                ('content', models.TextField()),
                ('category', models.CharField(blank=True, max_length=150, null=True)),
                ('reading_time', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=150, null=True)),
                ('subject', models.CharField(blank=True, max_length=150, null=True)),
                ('message', models.TextField()),
                ('status', models.CharField(blank=True, choices=[('not_attended', 'Not Attended'), ('attended', 'Attended')], default='not_attended', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nakshatras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('ruler', models.CharField(max_length=255)),
                ('symbol', models.CharField(blank=True, help_text='Nakshatra symbol e.g. Chariot', max_length=255, null=True)),
                ('deity', models.CharField(blank=True, help_text='Ruling deity e.g. Brahma', max_length=255, null=True)),
                ('ruling_planet', models.CharField(blank=True, help_text='Ruling planet e.g. Moon', max_length=255, null=True)),
                ('element', models.CharField(blank=True, help_text='Element e.g. Earth', max_length=255, null=True)),
                ('qualities', models.TextField(blank=True, help_text='Comma-separated qualities', null=True)),
                ('vastu_direction', models.CharField(blank=True, help_text='Best Vastu direction for this nakshatra', max_length=255, null=True)),
                ('best_plot_shape', models.CharField(blank=True, help_text='Best plot shape', max_length=255, null=True)),
                ('ideal_location', models.TextField(blank=True, help_text='Ideal location description', null=True)),
                ('favorable_colors', models.TextField(blank=True, help_text='Comma-separated favorable colors', null=True)),
                ('plot_recommendation', models.TextField(blank=True, help_text='Plot recommendation text', null=True)),
                ('icon', models.ImageField(blank=True, max_length=500, null=True, upload_to='nakshatra_icons')),
                ('icon_char', models.CharField(blank=True, choices=[('🐴', '🐴'), ('🔴', '🔴'), ('🔥', '🔥'), ('🐂', '🐂'), ('🦌', '🦌'), ('💧', '💧'), ('🏹', '🏹'), ('🌸', '🌸'), ('💚', '💚'), ('👑', '👑'), ('🛏️', '🛏️'), ('🌞', '🌞'), ('✋', '✋'), ('💎', '💎'), ('🌿', '🌿'), ('🌳', '🌳'), ('🌺', '🌺'), ('👂', '👂'), ('🦁', '🦁'), ('🌊', '🌊'), ('🐘', '🐘'), ('🥁', '🥁'), ('⭐', '⭐'), ('⚔️', '⚔️'), ('🐍', '🐍'), ('🐟', '🐟')], default='🐴', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_name', models.CharField(max_length=255)),
                ('plot_size', models.CharField(max_length=255)),
                ('plot_price', models.CharField(max_length=255)),
                ('plot_description', models.TextField()),
                ('plot_facing', models.CharField(max_length=255)),
                ('plot_status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('reserved', 'Reserved')], max_length=255)),
                ('plot_created_at', models.DateTimeField(auto_now_add=True)),
                ('plot_updated_at', models.DateTimeField(auto_now=True)),
                ('plot_image1', models.ImageField(blank=True, null=True, upload_to='plots/')),
                ('plot_image2', models.ImageField(blank=True, null=True, upload_to='plots/')),
                ('plot_image3', models.ImageField(blank=True, null=True, upload_to='plots/')),
                ('plot_image4', models.ImageField(blank=True, null=True, upload_to='plots/')),
                ('plot_image5', models.ImageField(blank=True, null=True, upload_to='plots/')),
                ('is_sold', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('plot_shape', models.CharField(blank=True, help_text='e.g. Square, Rectangle', max_length=255, null=True)),
                ('vastu_score', models.IntegerField(blank=True, help_text='Vastu score out of 100', null=True)),
                ('vastu_certified', models.BooleanField(default=False, help_text='Is this plot Vastu certified?')),
                ('rera_approved', models.BooleanField(default=False, help_text='Is this plot RERA approved?')),
                ('price_per_sqft', models.CharField(blank=True, help_text='Price per sq.ft', max_length=255, null=True)),
                ('clear_title', models.BooleanField(default=True, help_text='Clear title available')),
                ('bank_loan', models.BooleanField(default=True, help_text='Bank loan available')),
                ('legal_approvals', models.TextField(blank=True, help_text='Comma-separated list of approvals', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('goole_map_link', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nakshatra_plot_shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_shape', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nakshatra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plot_shapes', to='dashboard.nakshatras')),
            ],
        ),
        migrations.CreateModel(
            name='Nakshatra_directions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nakshatra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='dashboard.nakshatras')),
            ],
        ),
        migrations.CreateModel(
            name='plot_nearby_places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nearby_place', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.plots')),
            ],
        ),
        migrations.CreateModel(
            name='plot_highlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.plots')),
            ],
        ),
        migrations.CreateModel(
            name='plot_amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.plots')),
            ],
        ),
        migrations.AddField(
            model_name='plots',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.projects'),
        ),
        migrations.CreateModel(
            name='property_nakshatra_reasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nakshatra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.nakshatras')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.plots')),
            ],
        ),
        migrations.CreateModel(
            name='property_nakshatras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nakshatra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.nakshatras')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.plots')),
            ],
        ),
    ]
