# Generated by Django 5.2.10 on 2026-01-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_plotdocuments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_nakshatra_reasons',
            name='reason',
            field=models.TextField(),
        ),
    ]
