# Generated by Django 3.2.25 on 2026-01-23 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_property_nakshatra_reasons_reason'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blogs',
        ),
        migrations.DeleteModel(
            name='enquiry',
        ),
        migrations.RemoveField(
            model_name='nakshatra_plot_shape',
            name='nakshatra',
        ),
        migrations.RemoveField(
            model_name='plot_amenities',
            name='plot',
        ),
        migrations.RemoveField(
            model_name='plot_highlights',
            name='plot',
        ),
        migrations.RemoveField(
            model_name='plot_nearby_places',
            name='plot',
        ),
        migrations.RemoveField(
            model_name='plotdocuments',
            name='plot',
        ),
        migrations.RemoveField(
            model_name='plots',
            name='project',
        ),
        migrations.RemoveField(
            model_name='property_nakshatra_reasons',
            name='nakshatra',
        ),
        migrations.RemoveField(
            model_name='property_nakshatra_reasons',
            name='plot',
        ),
        migrations.RemoveField(
            model_name='property_nakshatras',
            name='nakshatra',
        ),
        migrations.RemoveField(
            model_name='property_nakshatras',
            name='plot',
        ),
        migrations.DeleteModel(
            name='Nakshatra_directions',
        ),
        migrations.DeleteModel(
            name='Nakshatra_plot_shape',
        ),
        migrations.DeleteModel(
            name='Nakshatras',
        ),
        migrations.DeleteModel(
            name='plot_amenities',
        ),
        migrations.DeleteModel(
            name='plot_highlights',
        ),
        migrations.DeleteModel(
            name='plot_nearby_places',
        ),
        migrations.DeleteModel(
            name='PlotDocuments',
        ),
        migrations.DeleteModel(
            name='Plots',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.DeleteModel(
            name='property_nakshatra_reasons',
        ),
        migrations.DeleteModel(
            name='property_nakshatras',
        ),
    ]
