# Generated by Django 3.2.25 on 2026-01-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_dashboard_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
    ]
