# Generated by Django 3.2.25 on 2026-01-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_enquiry_globalsetting_role_testimonial_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
