# Generated by Django 3.2.25 on 2026-01-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_role_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='testimonial_text',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='email',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='position',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='designation',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='company',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
