# Generated by Django 3.2.25 on 2026-01-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20260126_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='category',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='status',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='source',
            field=models.CharField(blank=True, choices=[('web', 'Web'), ('service', 'Service'), ('product', 'Product')], max_length=20),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
