# Generated by Django 3.2.25 on 2026-02-02 05:27

import dashboard.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20260126_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/dashboard/media/testimonials/', location='C:\\Users\\dell\\Desktop\\admin_basic\\website-builder\\dashboard\\media\\testimonials'), upload_to=dashboard.models.testimonial_image_upload_path),
        ),
    ]
