# Generated by Django 3.2.25 on 2026-02-02 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0002_auto_20260128_1749'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='slots.slot'),
        ),
        migrations.DeleteModel(
            name='BookingSlot',
        ),
    ]
