# Generated by Django 3.2.25 on 2026-01-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_enquiry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceenquiry',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='serviceenquiry',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='serviceenquiry',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='serviceenquiry',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='serviceenquiry',
            name='status',
        ),
        migrations.RemoveField(
            model_name='serviceenquiry',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='serviceenquiry',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='serviceenquiry',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
