# Generated by Django 3.2.25 on 2026-01-29 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_icon'),
        ('service_enquiry', '0002_auto_20260128_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceenquiry',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
    ]
