# Generated by Django 3.2.25 on 2026-02-02 05:27

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/products/media/products/', location='C:\\Users\\dell\\Desktop\\admin_basic\\website-builder\\products\\media\\products'), upload_to=products.models.product_image_upload_path),
        ),
    ]
